dataset_name: mosi
seed: 1
batch_size: 8
learning_rate: 5.0e-6
epochs: 30
patience: 8
dropout: 0.3
text_context_len: 2
audio_context_len: 1
hidden_size: 1024
video_feature_dim: 20
num_attention_heads: 16
temperature: 0.07
pure_weight: 0.1
bias_weight: 0.1
complete_weight: 0.1
log: logs/ivid.log
checkpoint_dir: checkpoint
save_model: true
